import json
import os
from datetime import datetime, timezone
from . import config


def _now():
    return datetime.now(timezone.utc).isoformat()


def load():
    if not os.path.exists(config.STATE_PATH):
        return default_state()
    with open(config.STATE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save(state):
    with open(config.STATE_PATH, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)
    render_status_md(state)


def default_state():
    return {
        "last_completed_by": "owner",
        "last_task": "Инициализация оркестратора",
        "active_running_experiment": None,
        "blocked_on": "executor",
        "next_action_owner": "architect",
        "next_action": None,
        "pending_decision": None,
        "history": [],
    }


def record(state, by, task):
    state["history"].append({"ts": _now(), "by": by, "task": task})
    state["history"] = state["history"][-50:]


def load_control():
    if not os.path.exists(config.CONTROL_PATH):
        return {"paused": False, "muted": False}
    with open(config.CONTROL_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save_control(c):
    with open(config.CONTROL_PATH, "w", encoding="utf-8") as f:
        json.dump(c, f, ensure_ascii=False, indent=2)


def render_status_md(state):
    md = (
        "# STATUS — live handoff (auto-generated by orchestrator)\n\n"
        f"Updated: {_now()}\n\n"
        "## Текущая очередь хода\n"
        f"- last_completed_by: {state['last_completed_by']}\n"
        f"- last_task: {state['last_task']}\n"
        f"- active_RUNNING_EXPERIMENT: {state['active_running_experiment']}\n"
        f"- blocked_on: {state['blocked_on']}\n"
        f"- next_action_owner: {state['next_action_owner']}\n"
        f"- next_action: {state['next_action']}\n"
        f"- pending_decision: {state['pending_decision']}\n\n"
        "## Контракт\n"
        "- DeepSeek действует только если next_action_owner == DeepSeek.\n"
        "- My3 действует только если next_action_owner == My3.\n"
        "- owner утверждает RUNNING_EXPERIMENT и переписывает STATUS.\n"
    )
    os.makedirs(os.path.dirname(config.STATUS_PATH) or ".", exist_ok=True)
    with open(config.STATUS_PATH, "w", encoding="utf-8") as f:
        f.write(md)
